parameters:
    ehdev.festival.festival.type.class: EHDev\Bundle\FestivalBasicsBundle\Form\Type\FestivalType

services:
#Types
    ehdev.festival.festival.form.type:
        class: "%ehdev.festival.festival.type.class%"
        tags:
            - { name: form.type, alias: "ehdev_festival" }
# Forms
    ehdev.festival.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "ehdev_festival_form"
            - "ehdev_festival"
