parameters:
    ehdev.festival.entity.festival.class: EHDev\FestivalBasicsBundle\Entity\Festival
    ehdev.festival.entity.stage.class: EHDev\FestivalBasicsBundle\Entity\Stage
    ehdev.festival.festival.manager.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    ehdev.festival.stage.manager.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    ehdev.festival.event.detailviewlistener.class: EHDev\FestivalBasicsBundle\EventListener\AbstractFestivalDetailViewListener

services:
    ehdev.festival.festival.manager:
        class: %ehdev.festival.festival.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ehdev.festival.entity.festival.class%
            - "@doctrine.orm.entity_manager"

    ehdev.festival.stage.manager:
        class: %ehdev.festival.stage.manager.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %ehdev.festival.entity.stage.class%
            - "@doctrine.orm.entity_manager"

    ehdev.festival.event.detailviewlistener:
        abstract: true
        arguments:
            - '@request_stack'
            - '@translator'
            - "@doctrine.orm.entity_manager"
