navigation:
    menu_config:
        items:
            ehdev_festival_tab:
                uri: '#'
                label: 'ehdev.festivalbasics.tab'
                position: 10
            ehdev_festival_festival_tab:
                label: 'ehdev.festivalbasics.festival.entity_plural_label'
                route:   'ehdev_festival_festival_index'
                extras:
                    icon: fa-puzzle-piece

            ehdev_festival_stage_tab:
                label: 'ehdev.festivalbasics.stage.entity_plural_label'
                route:   'ehdev_festival_stage_index'
                extras:
                    icon: fa-desktop
            ehdev_festival_securityarea_tab:
                label: 'ehdev.festivalbasics.securityarea.entity_plural_label'
                route: 'ehdev_festival_security_area_index'
                extras:
                    icon: fa-desktop
        tree:
            application_menu:
                children:
                    ehdev_festival_tab:
                        children:
                            ehdev_festival_festival_tab: ~
                            ehdev_festival_stage_tab: ~
                            ehdev_festival_securityarea_tab: ~

    titles:
        ehdev_festival_festival_index:  ~
        ehdev_festival_festival_view: 'Festival'
