navigation:
    menu_config:
        items:
            ehdev_festival_tab:
                uri: '#'
                label: 'ehdev.festivalbasics.tab'
                extras:
                    position: 50
            ehdev_festival_festival_tab:
                uri: '#'
                label: 'ehdev.festivalbasics.festival.entity_plural_label'
                route:   'ehdev_festival_festival_index'
                extras:
                    icon: fa-puzzle-piece
        tree:
            application_menu:
                children:
                    ehdev_festival_tab:
                        children:
                            ehdev_festival_festival_tab: ~
