datagrids:
    ehdev-festival-festival-grid:
        extended_entity_name: "%ehdev.festival.entity.festival.class%"
        acl_resource: ehdev_festival_festival_view
        source:
            type: orm
            query:
                select:
                    - fw.id
                    - fw.name
                    - fw.startDate
                    - fw.endDate
                    - fw.maxGuests
                    - fw.createdAt
                    - fw.updatedAt
                from:
                    - { table: "%ehdev.festival.entity.festival.class%", alias: fw }
        columns:
            id:
                label:         ehdev.festivalbasics.festival.id.label
            name:
                frontend_type: string
                label:         ehdev.festivalbasics.festival.name.label
            startDate:
                frontend_type: date
                label:         ehdev.festivalbasics.festival.start_date.label
            endDate:
                frontend_type: date
                label:         ehdev.festivalbasics.festival.end_date.label
            maxGuests:
                frontend_type: integer
                label:         ehdev.festivalbasics.festival.max_guests.label
            createdAt:
                frontend_type: date
                label:         ehdev.festivalbasics.festival.createdat.label
            updatedAt:
                frontend_type: date
                label:         ehdev.festivalbasics.festival.updatedat.label
        properties:
            id: ~
            view_link:
                type: url
                route: ehdev_festival_festival_view
                params: [ id ]
            update_link:
                type:       url
                route:      ehdev_festival_festival_update
                params:     [ id ]
            delete_link:
                type: url
                route: oro_api_delete_festival
                params: [ id ]
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                icon: eye
                link: view_link
                rowAction: true
            update:
                type: dialog
                label: oro.grid.action.update
                icon: edit
                link: update_link
                widgetOptions:
                    reload-grid-name: ehdev-festival-festival-grid
                    options:
                        dialogOptions:
                            title:  "@translator->trans(ehdev.festivalbasics.festival.widget.edit.title)"
                            modal:  true
                            width:  700
            delete:
                type:          delete
                acl_resource:  ehdev_festival_festival_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
