services:
    EHDev\FestivalBasicsBundle\ApiManager\FestivalAccountApiManager:
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            $om: '@Doctrine\Common\Persistence\ObjectManager'

    EHDev\FestivalBasicsBundle\ApiManager\FestivalApiManager:
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            $om: '@Doctrine\Common\Persistence\ObjectManager'

    EHDev\FestivalBasicsBundle\ApiManager\SecurityAreaApiManager:
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            $om: '@Doctrine\Common\Persistence\ObjectManager'

    EHDev\FestivalBasicsBundle\ApiManager\StageApiManager:
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            $om: '@Doctrine\Common\Persistence\ObjectManager'
