parameters:
    ehdev.festival.entity.festival.class: EHDev\FestivalBasicsBundle\Entity\Festival
    ehdev.festival.entity.stage.class: EHDev\FestivalBasicsBundle\Entity\Stage
    ehdev.festival.entity.security_area.class: EHDev\FestivalBasicsBundle\Entity\SecurityArea
    ehdev.festival.event.detailviewlistener.class: EHDev\FestivalBasicsBundle\EventListener\AbstractFestivalDetailViewListener

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    EHDev\FestivalBasicsBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Model,Resources,EHDevFestivalBasicsBundle.php}'

    EHDev\FestivalBasicsBundle\Controller\:
        public: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ehdev.festival.event.detailviewlistener:
        abstract: true
        arguments:
            - '@request_stack'
            - '@translator'
            - "@doctrine.orm.entity_manager"
